default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>

development:
  <<: *default
  database: gourmet_genie_development

test:
  <<: *default
  database: gourmet_genie_test

production:
  <<: *default
  database: gourmet_genie_production
