quantities:
  - '¼'
  - '½'
  - '¾'
  - '⅐'
  - '⅑'
  - '⅒'
  - '⅓'
  - '⅔'
  - '⅕'
  - '⅖'
  - '⅗'
  - '⅘'
  - '⅙'
  - '⅚'
  - '⅛'
  - '⅜'
  - '⅝'
  - '⅞'

units:
  - 'cup'
  - 'tablespoon'
  - 'teaspoon'
  - 'ounce'
  - 'pound'
  - 'gram'
  - 'kg'
  - 'ml'
  - 'l'
  - 'clove'
  - 'slice'
  - 'piece'